version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app_network

  app:
    build: .
    container_name: node_app
    restart: always
    depends_on:
      - db
    environment:
      DB_URI: ${DB_URI}  # Uses the DB_URI from your local environment
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge