apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: node-app-monitor
  labels:
    release: prometheus  
spec:
  selector:
    matchLabels:
      app: node-app
  podMetricsEndpoints:
    - port: web
      path: /metrics
      interval: 10s